# @format

language: node_js
node_js:
  - 12
script: true
branches:
  only:
    - master
deploy: # see README for details on these keys
  skip_cleanup: true
  provider: heroku
  app: mapitapp
  api_key:
    secure: PKVzAqW40Wrnk23iJMWLC72fsJgli1Ov5JmIPVPcQ/FbdJH5wkH9gmDhak4AxCuPDNYKGQ55EA6mPt0ufNRk/UoZBIsb3wqaESRIl/f8HpF9f9Jebl4SXfv0H9q2Ac9fcWG2uHB719YpK1BgRDti8W8cEnQ54pGHYTaXY25UPMAakpMxcY70k87i6lST+ZL6BE6XQhV56G/EYq2N8hwxA1RVMhDS60wUbuqgiZf7Hu+SFg53YlFwYL6GU4PVizKxZJzNgm2jUrMo8JpZ6FMeUrCUt6Lk55CFkkrf7fx/BPaUVomBV2yF/SxWmREhlXR0XHufZv4tkfiSypxHukjQKcrK38FAKFkbgxugR2+/KCA+PDcK0GsCyzszYKzZExxennYVDUm+KqvWnEtQvqc+27amSkd2ZI0i+ECF8F3vZpOWN+XIcWg0lyEcDu1payMducMt7fJpJIjVcsSbsWf8NrIrCgp5BDrEdFFigr9YBdxp8qQSO9isgpUA9OBtR1623MYMP4X47lVZTwcOtPRD96S0nR9L3ipmUmjEQWcLboAlPwTUrnRY0GjFzjmhAvUsxPllH4Bi5nPzxNX9/pLFMfSAXBLQS77ee5g6OA3/oWZ09IKgudHYFAP/E17rDjsnsFpYbOb0lWu3H4AMhqpYdFeVhoqcbJtvVBhegLt3e0s=
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
