# @format

language: node_js
node_js:
  - 12
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: mapitapp
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: b7JnuYXA5LpjJH27U8+8kDoD8CBgI0J93pQLAKGQNK0eh1dUlT7Ajact79Ok0293J3A5xosCDx1G6ky/Bw5hHXzEDHHQygZzLs8yVv4d980IaC28dZPAsbH0Tt3wyJ79J9nGEQi2oc7bgFULqnnef4vc2PQH7jZt+V8+ueeL2HBUEnWi5qYwdu7jfmzNpNxMOExieMhI8IB+uXjYGDgYzI186+tIuAefIFcKgmqd5wnKUiATadEQAQGvHQQMNG5SeFxbAQDlVXNl0W1JkazqLifhLiF9w5GB1U+TOl52NV5H8xrlNUTsCVIH4QOcHsHE8fXE1P0PRjiiPXrRLu9pJ50n+8LiFTNCLkaF1d41xb6NntqiDMz1qkJ+GAAKv1J0juht5k6ct2hm9yITMDwiIFEFlEHcHUScbiOeWe3v0vKDnOBnbyFflE0V+MoBhfyoeCWXGjU0sz47NbTP8TojdQtLHuKP+RuDEwsXMBpS8LgbLn9ObLn4NgWiPgmUTFVTbWp69DPcY11WqUNTSQIhi9i/gdhKeGH+7qFqWn2uABRAhsXwYahVveHlpBxdFbHkjatMdFjt5tF5PYNDwRW5BokBdhLbxU64bXjDgVXaVhnjgn0vgTiF6y0TksMx6amJX9809/V2HI3F6znnZc3Ms2sjRqozftgwS5FbIzzDx6I=
