# @format

language: node_js
node_js:
  - 'stable'
script: true
deploy:
  skip_cleanup: true
  provider: heroku
  app: mapitapp
  api_key:
      secure: "BlpA9iT5XL9l+pgsQaQhfAuCMz2sNqK7vvn8IhPpnZxGOmjYoURLdrLBVmEQwS8q1WEmIrvf85+8mF4VROGgQn7Z5U9GEBF4vTLd8v4nsirm5/kLlpMRf/ap8G1I12PqEkUbZV4zqiwd3NBNwAfnigqPMaF9+W/HbRMnsv9SDkWnIlsEbZC808B0sbt6WdusFmIo2RoFJUCGArpOZmkSWn7DZwt+qWpZ30cs/JiVM08yjh2TMEdPewOt/W0Oawqb3XwNpT5IdZ4AP+Ax2DGUo8xAEZ3SeNQ1UFnVQ1CGXN4Wz+tKduKfuHTR5+82SaCn1fbOkbaGlF2mz0RXi+vbFVxELHfTnpB3yMc61cNoNBQI5ydG/xvdqC9xcRockFwBworwdu7xbpUIJ10V5X+R52ZQOtAbAKfpKXGLR2Qs1N7A7fJv9hUmy+sPJhXypVq4L0SyyGdMIoTERMjWJDUrVt9n8LEjRZ5CU/f+L9dYx8+ty4iq1bSQNNlBDtXYTJFMGWHokDXhGibwwXOS38tJFOescyjjCSacjskQxkUc30z7t4VxCxvcnsbTd8Bed/gzkzVw1F/oO6RicH/2IpxzTrSW/55Cfwb86w+dnbnWi1fJX8JdlaDZ8gqvpXS/IESlbAXxHclTL4U7HdcLU0gq+KJZTVmcDvgrd5yhHiLXuKw="
  on:
    branch: master
